free-ticket:
  enabled: false
  amount: 5
  every: 86400
room-settings:
  waiting-time: 15
  intermission-time: 20
room-create-cooldown: 240
spawn-location: world 0 128 0
allowed-commands:
  - heal
  - feed
  - phoban
  - tell
  - r
  - w
  - msg
  - repair
  - fix
  - discord
  - skill
debug-level: 0