name: "&aAngry Sludge"
icon: slime_ball
description:
  - "&7Angry Sludge là con boss cực mạnh."
spawn-location: world 0 128 0
queue-location: world 0 128 0
requirement: "room1:easy"
region: "room2"
levels:
  easy:
    min-players: 1
    max-players: 5
    playing-time: 1800
    respawn-time: 10
    respawn-chances: 3
    boss-id: "AngrySludge"
    mobs:
      - zombie @amount=3 @every=10 @delay=10
      - zombie world 0 128 0 @amount=10
      - AngrySludge world 0 128 0 @delay=10
      - StaticallyChargedSheep world 0 128 0 @delay=10
    win-rewards:
      - eco give {player} 10000
  medium:
    min-players: 1
    max-players: 5
    playing-time: 1400
    respawn-time: 10
    respawn-chances: 2
    boss-id: "AngrySludge"
    mobs:
      - zombie @amount=5 @every=10 @delay=10
      - zombie world 0 128 0 @amount=15
      - AngrySludge:1 world 0 128 0 @delay=10
      - StaticallyChargedSheep:1 world 0 128 0 @delay=10
    win-rewards:
      - eco give {player} 20000
  hard:
    min-players: 2
    max-players: 3
    playing-time: 1200
    respawn-time: 20
    respawn-chances: 1
    boss-id: "AngrySludge"
    mobs:
      - zombie @amount=5 @every=5 @delay=10
      - zombie world 0 128 0 @amount=30
      - AngrySludge:2 world 0 128 0 @delay=10
      - StaticallyChargedSheep:2 world 0 128 0 @delay=10
    win-rewards:
      - eco give {player} 30000