name: "&eGod Skeleton"
icon: bone
description:
  - "&7God Skeleton là con boss cực mạnh."
spawn-location: world 0 128 0
region: "room1"
levels:
  easy:
    min-players: 1
    max-players: 5
    preparing-time: 10
    playing-time: 1800
    respawn-chances: 3
    boss: "god-skeleton:1"
    mobs:
      - zombie @amount=3 @every=10 @delay=10
      - zombie world 0 128 0 @amount=10
      - godSkeletonMinion world 0 128 0 @delay=300
    win-rewards:
      - eco give {player} 10000
  medium:
    min-players: 1
    max-players: 5
    preparing-time: 10
    playing-time: 1400
    respawn-chances: 2
    boss: "god-skeleton:2"
    mobs:
      - zombie @amount=5 @every=10 @delay=10
      - zombie world 0 128 0 @amount=15
      - godSkeletonMinion world 0 128 0 @delay=300
    win-rewards:
      - eco give {player} 20000
  hard:
    min-players: 1
    max-players: 3
    preparing-time: 5
    playing-time: 1200
    respawn-chances: 1
    boss: "god-skeleton:3"
    mobs:
      - zombie @amount=5 @every=5 @delay=10
      - zombie world 0 128 0 @amount=30
      - godSkeletonMinion world 0 128 0 @delay=300
    win-rewards:
      - eco give {player} 30000