title: "&0&lChọn độ khó"
layout:
  - "---------"
  - "---xxx---"
  - "----q----"
components:
  "-":
    material: BLACK_STAINED_GLASS_PANE
    name: "&a"
  "x":
    type: difficulty
    material: BLACK_STAINED_GLASS_PANE
    name: "&a{dungeon} &7({difficulty}&7)"
  "q":
    type: quit
    material: barrier
    name: "&eQuay về"
    lore:
      - ""
      - "&fQuay về menu chính"

room-locked-trailer:
  - ""
  - "&eThông tin:"
  - "&c&l ✕&7 Phó bản này chưa được mở khoá!"
  - "&7 ▪ &cYêu cầu: &7{requiredRoom}&7 mức độ {requiredDifficulty}"
  - ""

room-lore-trailer:
  - ""
  - "&eThông tin:"
  - "&7 ▪ Người chơi: &f{currentPlayers}/{maxPlayers}"
  - "&7 ▪ Trạng thái: {stage}"
  - "&7 ▪ Độ khó: {difficulty}"
  - ""
  - "&eLịch sử:"
  - "&7 ▪ Bạn đã chơi &f{playTimes}&7 lần"
  - "&7 ▪ Thắng &f{wins}&7 trận &7({winRatio})"
  - "&7 ▪ Kết quả tốt nhất là &f{bestCompleteTime}"
  - ""
  - "&e> Nhấn để tạo phòng"
  - "&7  Tiêu hao &c{ticketCost}&7 vé"
