title: "&0&lChọn độ khó"
layout:
  - "---------"
  - "--xxxxx--"
  - "---------"
  - "----q---I"
components:
  "-":
    material: black_stained_glass_pane
    name: "&a"
  "x":
    type: difficulty
    material: black_stained_glass_pane
    name: "&a"
  "q":
    type: quit
    material: barrier
    name: "&eQuay về"
    lore:
      - ""
      - "&fQuay về menu chính"
  "I":
    type: info
    material: book
    name: "&aThông tin"
    lore:
      - "&7▪ Vé Phó bản: &f%phoban_tickets%"
      - "&7▪ Tổng số trận: &f%phoban_total_matches%"
      - "&7   Thắng: &f%phoban_total_wins%"
      - "&7   Thua: &f%phoban_total_losses%"
      - ""
      - "&eNhấn để mở shop mua vé Phó Bản"

difficulty-name: "&a{dungeon} &7| {difficulty} {challengeLevel}"

room-locked-trailer:
  - ""
  - "&eThông tin:"
  - "&c&l ✕&7 Phó bản này chưa được mở khoá!"
  - "&7 ▪ &cYêu cầu: &7{requiredRoom}&7 mức độ {requiredDifficulty}"

room-lore-trailer:
  - ""
  - "&eThông tin:"
  - "&7 ▪ Người chơi: &f{currentPlayers}/{maxPlayers}"
  - "&7 ▪ Trạng thái: {stage}"
  - "&7 ▪ Độ khó: {difficulty} {challengeLevel}"
  - ""
  - "&eLịch sử:"
  - "&7 ▪ Bạn đã chơi &f{playTimes}&7 lần"
  - "&7 ▪ Thắng &f{wins}&7 trận &7({winRatio})"
  - "&7 ▪ Kết quả tốt nhất là &f{bestCompleteTime}"
  - ""
  - "&e> Nhấn để tạo phòng"
  - "&7&o  Tiêu hao &c&o{ticketCost}&7&o vé"
  - "&7&o  CHÚ Ý: Làm trống túi để nhận quà thưởng!"