title: "&0&lSảnh Phó Bản"
layout:
  - "---------"
  - "-xxxxxxx-"
  - "-xxxxxxx-"
  - "---------"
components:
  "-":
    material: BLACK_STAINED_GLASS_PANE
    name: "&a"
  "x":
    type: room
    material: BLACK_STAINED_GLASS_PANE
    name: "&a"

room-lore-trailer:
  available:
    - ""
    - "&eThông tin:"
    - "&7 ▪ Phòng trống chưa bắt đầu!"
    - ""
    - "&eLịch sử:"
    - "&7 ▪ Bạn đã chơi &f{playTimes}&7 lần"
    - "&7 ▪ Kết quả tốt nhất: &f{bestCompleteTime}"
    - ""
    - "&e> Nhấn để tham gia"
  waiting:
    - ""
    - "&eThông tin:"
    - "&7 ▪ Người chơi: &f{currentPlayers}/{maxPlayers}"
    - "&7 ▪ Trạng thái: {stage}"
    - "&7 ▪ Độ khó: {difficulty}"
    - ""
    - "&eLịch sử:"
    - "&7 ▪ Bạn đã chơi &f{playTimes}&7 lần"
    - "&7 ▪ Kết quả tốt nhất: &f{bestCompleteTime}"
    - ""
    - "&e> Nhấn để tham gia"
  playing:
    - ""
    - "&eThông tin:"
    - "&7 ▪ Người chơi: &f{currentPlayers}/{maxPlayers}"
    - "&7 ▪ Trạng thái: {stage}"
    - "&7 ▪ Độ khó: {difficulty}"
    - "&7 ▪ Thời gian còn lại: &f{timeLeft}"
    - ""
    - "&eLịch sử:"
    - "&7 ▪ Bạn đã chơi &f{playTimes}&7 lần"
    - "&7 ▪ Kết quả tốt nhất: &f{bestCompleteTime}"
    - ""
  ending:
    - ""
    - "&eThông tin:"
    - "&7 ▪ Người chơi: &f{currentPlayers}/{maxPlayers}"
    - "&7 ▪ Trạng thái: {stage}"
    - "&7 ▪ Độ khó: {difficulty}"
    - "&7 ▪ Thời gian còn lại: &f{timeLeft}"
    - ""
    - "&eLịch sử:"
    - "&7 ▪ Bạn đã chơi &f{playTimes}&7 lần"
    - "&7 ▪ Kết quả tốt nhất: &f{bestCompleteTime}"
    - ""