title: "&0&lSảnh Phó Bản"
layout:
  - "---------"
  - "-xxxxxxx-"
  - "-xxxxxxx-"
  - "--------I"
components:
  "-":
    material: black_stained_glass_pane
    name: "&a"
  "x":
    type: room
    material: black_stained_glass_pane
    name: "&a"
  "I":
    type: info
    material: book
    name: "&aThông tin"
    lore:
      - "&7▪ Vé Phó bản: &f%phoban_tickets%"
      - "&7▪ Tổng số trận: &f%phoban_total_matches%"
      - "&7   Thắng: &f%phoban_total_wins%"
      - "&7   Thua: &f%phoban_total_losses%"
      - ""
      - "&eNhấn để mở shop mua vé Phó Bản"

room-locked-trailer:
  available:
   - ""
   - "&eThông tin:"
   - "&c&l ✕&7 Phó bản này chưa được mở khoá!"
   - "&7 ▪ &cYêu cầu: &7{requiredRoom}&7 mức độ {requiredDifficulty}&7 trở lên"
  waiting:
    - ""
    - "&eThông tin:"
    - "&7 ▪ Người chơi: &f{currentPlayers}/{maxPlayers}"
    - "&7 ▪ Trạng thái: {stage}"
    - "&7 ▪ Độ khó: {difficulty}"
    - ""
    - "&c&l ✕&7 Phó bản này chưa được mở khoá!"
    - "&7 ▪ &cYêu cầu: &7{requiredRoom}&7 mức độ {requiredDifficulty}&7 trở lên"
  playing:
    - ""
    - "&eThông tin:"
    - "&7 ▪ Người chơi: &f{currentPlayers}/{maxPlayers}"
    - "&7 ▪ Trạng thái: {stage}"
    - "&7 ▪ Độ khó: {difficulty}"
    - "&7 ▪ Thời gian còn lại: &f{timeLeft}"
    - ""
    - "&c&l ✕&7 Phó bản này chưa được mở khoá!"
    - "&7 ▪ &cYêu cầu: &7{requiredRoom}&7 mức độ {requiredDifficulty}&7 trở lên"
  ending:
    - ""
    - "&eThông tin:"
    - "&7 ▪ Người chơi: &f{currentPlayers}/{maxPlayers}"
    - "&7 ▪ Trạng thái: {stage}"
    - "&7 ▪ Độ khó: {difficulty}"
    - "&7 ▪ Thời gian còn lại: &f{timeLeft}"
    - ""
    - "&c&l ✕&7 Phó bản này chưa được mở khoá!"
    - "&7 ▪ &cYêu cầu: &7{requiredRoom}&7 mức độ {requiredDifficulty}&7 trở lên"

room-lore-trailer:
  available:
    - ""
    - "&eThông tin:"
    - "&a&l ✔&7 Phòng trống chưa bắt đầu"
    - ""
    - "&eLịch sử:"
    - "&7 ▪ Bạn đã chơi &f{playTimes}&7 lần"
    - "&7 ▪ Thắng &f{wins}&7 trận &7({winRatio})"
    - "&7 ▪ Kết quả tốt nhất: &f{bestCompleteTime}"
    - ""
    - "&e> Nhấn để chọn độ khó"
  waiting:
    - ""
    - "&eThông tin:"
    - "&7 ▪ Người chơi: &f{currentPlayers}/{maxPlayers}"
    - "&7 ▪ Trạng thái: {stage}"
    - "&7 ▪ Độ khó: {difficulty}"
    - ""
    - "&eLịch sử:"
    - "&7 ▪ Bạn đã chơi &f{playTimes}&7 lần"
    - "&7 ▪ Thắng &f{wins}&7 trận &7({winRatio})"
    - "&7 ▪ Kết quả tốt nhất: &f{bestCompleteTime}"
    - ""
    - "&e> Nhấn để tham gia"
    - "&7&o  Tiêu hao &c&o{ticketCost}&7&o vé"
    - "&7&o  CHÚ Ý: Làm trống túi để nhận quà thưởng!"
  playing:
    - ""
    - "&eThông tin:"
    - "&7 ▪ Người chơi: &f{currentPlayers}/{maxPlayers}"
    - "&7 ▪ Trạng thái: {stage}"
    - "&7 ▪ Độ khó: {difficulty}"
    - "&7 ▪ Thời gian còn lại: &f{timeLeft}"
    - ""
    - "&eLịch sử:"
    - "&7 ▪ Bạn đã chơi &f{playTimes}&7 lần"
    - "&7 ▪ Thắng &f{wins}&7 trận &7({winRatio})"
    - "&7 ▪ Kết quả tốt nhất: &f{bestCompleteTime}"
    - ""
    - "&c[ Phó bản đã bắt đầu ]"
  ending:
    - ""
    - "&eThông tin:"
    - "&7 ▪ Người chơi: &f{currentPlayers}/{maxPlayers}"
    - "&7 ▪ Trạng thái: {stage}"
    - "&7 ▪ Độ khó: {difficulty}"
    - "&7 ▪ Thời gian còn lại: &f{timeLeft}"
    - ""
    - "&eLịch sử:"
    - "&7 ▪ Bạn đã chơi &f{playTimes}&7 lần"
    - "&7 ▪ Thắng &f{wins}&7 trận &7({winRatio})"
    - "&7 ▪ Kết quả tốt nhất: &f{bestCompleteTime}"
    - ""
    - "&c[ Phó bản đã bắt đầu ]"

room-lore-trailer-overfull:
  - ""
  - "&eThông tin:"
  - "&7 ▪ Người chơi: &f{currentPlayers}/{maxPlayers}"
  - "&7 ▪ Trạng thái: {stage}"
  - "&7 ▪ Độ khó: {difficulty}"
  - "&7 ▪ Thời gian còn lại: &f{timeLeft}"
  - ""
  - "&eLịch sử:"
  - "&7 ▪ Bạn đã chơi &f{playTimes}&7 lần"
  - "&7 ▪ Thắng &f{wins}&7 trận &7({winRatio})"
  - "&7 ▪ Kết quả tốt nhất: &f{bestCompleteTime}"
  - ""
  - "&e> Nhấn để tham gia"
  - "&7&o  Tiêu hao &c&o{ticketCost}&7&o vé"
  - "&7&o  CHÚ Ý: Làm trống túi để nhận quà thưởng!"
